CREATE DATABASE FOOTBALLCLUBDB;
USE FOOTBALLCLUBDB;

-- Create Tables
CREATE TABLE VENUE (
    VENUE_ID INT PRIMARY KEY AUTO_INCREMENT,
    VENUE_NAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL,
    CITY VARCHAR(30) NOT NULL,
    CAPACITY INT NOT NULL CHECK(CAPACITY > 0)
);

CREATE TABLE CLUB (
    CLUB_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLUB_NAME VARCHAR(255) NOT NULL UNIQUE,
    COUNTRY VARCHAR(20) NOT NULL,
    FOUNDED DATE NOT NULL,
    VENUE_ID INT,
    FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID)
);

CREATE TABLE AGENT (
    AGENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
    NATIONALITY VARCHAR(20) NOT NULL,
    PHONE_NO VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE STAFF (
    SID INT PRIMARY KEY AUTO_INCREMENT,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    NATIONALITY VARCHAR(20) NOT NULL,
    SALARY FLOAT NOT NULL CHECK(SALARY > 0),
    CONTRACT_STARTDATE DATE NOT NULL,
    CONTRACT_ENDDATE DATE NOT NULL
);

CREATE TABLE MANAGER (
    SID INT PRIMARY KEY,
    CLUB_ID INT,
    FOREIGN KEY (SID) REFERENCES STAFF(SID),
    FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID)
);

CREATE TABLE COACH (
    SID INT PRIMARY KEY,
    SPECIALIZATION VARCHAR(20),
    CLUB_ID INT,
    FOREIGN KEY (SID) REFERENCES STAFF(SID),
    FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID)
);

CREATE TABLE PLAYER (
    SID INT PRIMARY KEY,
    POSITION VARCHAR(3) NOT NULL,
    GOALS INT DEFAULT 0 CHECK(GOALS >= 0),
    ASSISTS INT DEFAULT 0 CHECK(ASSISTS >= 0),
    JERSEY_NO INT,
    AGENT_ID INT,
    CLUB_ID INT,
    FOREIGN KEY (SID) REFERENCES STAFF(SID),
    FOREIGN KEY (AGENT_ID) REFERENCES AGENT(AGENT_ID),
    FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID),
    UNIQUE (JERSEY_NO, CLUB_ID)
);

CREATE TABLE REFEREE (
    REF_ID INT PRIMARY KEY AUTO_INCREMENT,
    FNAME VARCHAR(20) NOT NULL,
    LNAME VARCHAR(20) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    NATIONALITY VARCHAR(20) NOT NULL,
    SALARY FLOAT NOT NULL CHECK(SALARY > 0),
    EXPERIENCE_IN_YEARS INT NOT NULL DEFAULT 0 CHECK(EXPERIENCE_IN_YEARS >= 0)
);

CREATE TABLE TOURNAMENT (
    TID INT PRIMARY KEY AUTO_INCREMENT,
    TNAME VARCHAR(255) NOT NULL UNIQUE,
    REGION VARCHAR(20) NOT NULL,
    NO_OF_TEAMS INT NOT NULL CHECK(NO_OF_TEAMS >= 2)
);

CREATE TABLE RECORDS (
    RID INT PRIMARY KEY AUTO_INCREMENT,
    TID INT NOT NULL,
    SEASON VARCHAR(9) NOT NULL,
    TOP_SCORER_ID INT NOT NULL,
    TOP_ASSISTER_ID INT NOT NULL,
    WINNER_ID INT NOT NULL,
    FOREIGN KEY (TID) REFERENCES TOURNAMENT(TID),
    FOREIGN KEY (TOP_SCORER_ID) REFERENCES PLAYER(SID),
    FOREIGN KEY (TOP_ASSISTER_ID) REFERENCES PLAYER(SID),
    FOREIGN KEY (WINNER_ID) REFERENCES CLUB(CLUB_ID)
);

CREATE TABLE FOOTBALL_MATCH (
    MATCH_ID INT PRIMARY KEY AUTO_INCREMENT,
    HOME_TEAM_ID INT NOT NULL,
    AWAY_TEAM_ID INT NOT NULL,
    TOURNAMENT_ID INT,
    VENUE_ID INT NOT NULL,
    TIME_OF_MATCH DATETIME NOT NULL,
    REF_ID INT NOT NULL,
    HOME_GOALS INT DEFAULT 0,
    AWAY_GOALS INT DEFAULT 0,
    WINNER_ID INT,
    FOREIGN KEY (HOME_TEAM_ID) REFERENCES CLUB(CLUB_ID),
    FOREIGN KEY (AWAY_TEAM_ID) REFERENCES CLUB(CLUB_ID),
    FOREIGN KEY (WINNER_ID) REFERENCES CLUB(CLUB_ID),
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENT(TID),
    FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID),
    FOREIGN KEY (REF_ID) REFERENCES REFEREE(REF_ID)
);

CREATE TABLE TRANSFERS (
    TRANSFER_NO INT PRIMARY KEY AUTO_INCREMENT,
    SID INT,
    OLD_CLUB_ID INT,
    NEW_CLUB_ID INT,
    FOREIGN KEY (SID) REFERENCES STAFF(SID),
    FOREIGN KEY (OLD_CLUB_ID) REFERENCES CLUB(CLUB_ID),
    FOREIGN KEY (NEW_CLUB_ID) REFERENCES CLUB(CLUB_ID)
);

CREATE TABLE LEAGUE_TABLE (
    TID INT,
    CLUB_ID INT,
    GAMES_PLAYED INT,
    GAMES_WON INT,
    GAMES_DREW INT,
    GAMES_LOST INT,
    POINTS INT,
    PRIMARY KEY (TID, CLUB_ID),
    FOREIGN KEY (TID) REFERENCES TOURNAMENT(TID),
    FOREIGN KEY (CLUB_ID) REFERENCES CLUB(CLUB_ID)
);
